name: Test Community Contribution Label

on:
  issues:
    types: [assigned, unassigned]

jobs:
  call-label-action:
    uses: learningequality/.github/.github/workflows/community-contribution-label.yml@main
    secrets:
        token: ${{ secrets.WORKFLOW_PAT }}