name: "Unassign Inactive Contributors"
run-name: Unassign Inactive Contributors

on:
  schedule:
    - cron: "*/2 * * * *" # Every 2 minutes - for testing
  workflow_dispatch:

jobs:
  unassign-inactive:
    uses: learningequality/.github/.github/workflows/unassign-inactive-issues.yaml@main
    secrets:
      LE_BOT_APP_ID: ${{ secrets.LE_BOT_APP_ID }}
      LE_BOT_PRIVATE_KEY: ${{ secrets.LE_BOT_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}