name: "Unassign Inactive Contributors"
run-name: Unassign Inactive Contributors

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minute
  workflow_dispatch:

jobs:
  unassign-inactive:
    uses: learningequality/.github/.github/workflows/unassign-inactive-issues.yaml@main  
    secrets:
       WEB_Token: ${{ secrets.NEW_TOKEN }}